[sensor]
# shimmer can be used to control the backlight even without
# a light sensor. This happens when the specified path is not found,
# so to disable the automatic control just put
# path = ""
path = "/sys/bus/iio/devices/iio:device0"
[sensor.bounds]
# the sensor values for which the brightness will be min/max
min = 0
max = 500
[sensor.params]
# controls how fast the brightness is updated. This parameter
# has more influence for bigger changes in ambient light
# smoothness >= 1
smoothness = 10
# how convex is the function mapping sensor readings to brightness values
# lower values mean more convexity: brightness varies more with lower ambient light
# convexity > 0
convexity = 125
